### ISSUE TITLE
[Enhancement] Use more splits while training with larger datasets

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs-rs#106]
Context: https://github.com/open-spaced-repetition/fsrs-rs/pull/95#issuecomment-1742423201

It seems that the previous conversation ended before the idea was evaluated well enough.

**Comment by dae** [comment]
This may not be the improvement I originally thought it would be, as increasing the number of splits also increases the total number of revlogs that need to be processed - it doesn't simply divide the same amount of work up over more cores.

**Comment by user1823** [comment]
So, should this issue be closed? Or do you have any other idea?

**Comment by L-M-Sherlock** [comment]
I agree with dae. I have run the benchmark with more splits, but it doesn't improve the model significantly.
