### ISSUE TITLE
Enhancement: Include incomplete revlogs even when training

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs-rs#114]
In the past, I suggested excluding the incomplete revlogs from training because we didn't have any reasonable formula to calculate their memory states. However, now we do have a formula. So, including these revlogs makes sense now.

Corruption of the weights is not really a problem (now) because the effect of these revlogs on the weights will depend on their number. And if a user has a large number of such cards (for e.g. they deleted the old revlogs for most of their cards), they will want the optimizer to ensure that the RMSE is minimized for these cards as well.

The only problem I see is that the weights will depend on the input value of SM-2 retention.

**Comment by L-M-Sherlock** [comment]
It’s necessary to include them?

**Comment by user1823** [comment]
I know that this issue is closed but I still wanted to mention why I now think that this was a bad idea (for future reference).

RMSE or log loss is not an absolute measure of accuracy. With this idea, I was trying to minimize these metrics. 

Surely, the optimizer would have succeeded in decreasing the values of the metrics. But, by working on incomplete revlogs, the optimizer could not have obtained accurate values of the parameters; it would just get some values that minimize the log loss.

I think using the default weights or training on complete revlogs is much better than training on "garbage".
