### ISSUE TITLE
Consider time-frame limitation?

### ISSUE THREAD

**Issue by dae** [open-spaced-repetition/fsrs-rs#117]
Currently we require at least 1000 reviews to train. A very enthusiastic user could potentially do that in a few days if they introduced many new cards, but the review history would not result in useful weights. Perhaps we should also require a minimum time span of, say, 1 month between earliest and latest review?

**Comment by L-M-Sherlock** [comment]
> A very enthusiastic user could potentially do that in a few days if they introduced many new cards, but the review history would not result in useful weights.

I think these data could result in useful weights, particularly for w[0:4].

**Comment by user1823** [comment]
> I think these data could result in useful weights, particularly for w[0:4]. 

Yes, but the other weights will remain largely unchanged.

**Comment by user1823** [comment]
Thinking more about it, I don't think that it is worse than using the default weights; it might even be better.
