### ISSUE TITLE
Skip reviews with time = 0 when calculating average answer times

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs-rs#126]
Got this idea from: https://github.com/open-spaced-repetition/fsrs4anki/issues/540#issuecomment-1822175088

But, this suggestion also solves other issues (there can be other causes of Time = 0 too).

Rationale: No card can be answered in 0 s. So, such a time indicates that there is something abnormal with it. So, it is better to not include it in the average answer times.

To be clear, I want such reviews to be used for calculating the average Again/Hard/Good/Easy rates. Just don't use the time in the calculation of average times.

**Comment by L-M-Sherlock** [comment]
The revlog collector is implemented in Anki. So you need to submit this issue to @dae
