### ISSUE TITLE
User guide

### ISSUE THREAD

**Issue by jawadkho** [open-spaced-repetition/fsrs-rs#133]
This look promising!

Are there plans to write a user guide? If so, any timeline in mind?

**Comment by L-M-Sherlock** [comment]
I don't know how to write the user guide, because only Anki uses this crate.

**Comment by L-M-Sherlock** [comment]
Here is the API of FSRS-rs crate:

https://github.com/open-spaced-repetition/fsrs-rs/blob/main/src/lib.rs

If you have any question about them, please feel free to ask here.

**Comment by asukaminato0721** [comment]
if you only need that algorithm, check <https://github.com/open-spaced-repetition/rs-fsrs>
