### ISSUE TITLE
Add an option to turn off outlier filter when benchmark

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/fsrs-rs#136]
The outlier filter has been applied in benchmark dataset. But current FSRS-rs applies the outlier filter inside the API. So the outlier filter is applied twice, which is unintended. @dae, could help me add an option to turn off outlier filter when benchmark?

**Comment by dae** [comment]
Simplest approach would be to control it with an env var, e.g.

```diff
diff --git a/src/dataset.rs b/src/dataset.rs
index dcf047e..71a9f28 100644
--- a/src/dataset.rs
+++ b/src/dataset.rs
@@ -139,6 +139,9 @@ pub fn filter_outlier(
     pretrainset: Vec<FSRSItem>,
     mut trainset: Vec<FSRSItem>,
 ) -> (Vec<FSRSItem>, Vec<FSRSItem>) {
+    if std::env::var("FSRS_NO_OUTLIER").is_ok() {
+        // skip outlier filtering...
+    }
     let mut groups = HashMap::<u32, HashMap<u32, Vec<FSRSItem>>>::new();
 
     // group by rating of first review and delta_t of second review
```

Then you could set FSRS_NO_OUTLIER=1 when running the benchmark.
