### ISSUE TITLE
Reference usage?

### ISSUE THREAD

**Issue by aehlke** [open-spaced-repetition/fsrs-rs#151]
I'd love to integrate this work into my iOS projects however I'm unfamiliar with Rust and the mechanics of the FSRS optimizer. Is there documentation or another project integrating the optimizer from this that I can reference to understand how to use this? Thanks

**Comment by L-M-Sherlock** [comment]
AnkiMobile has integrated FSRS-rs into iOS. But it's not open source.

**Comment by aehlke** [comment]
Thanks, I found that they have a reference integration in the open source rust core.

**Comment by dae** [comment]
Please note that if you use Anki's code as a reference for your work, your work will need to be under a compatible license.

**Comment by aehlke** [comment]
@dae absolutely - I only saw what the entrypoint to fsrs-rs is (`compute_weights`) and have not referenced any implementation within anki

**Comment by dae** [comment]
You don't need to poke in Anki's code to determine that - the public API can be seen in the docs, and now that Jarrett has published the crate, the docs can even be viewed online. https://docs.rs/fsrs/latest/fsrs/
