### ISSUE TITLE
Pre-training Only when the number of reviews is less than 1000

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/fsrs-rs#152]
As we know, Anki set a limit of reviews for optimizing FSRS:

<img width="260" alt="image" src="https://github.com/open-spaced-repetition/fsrs-rs/assets/32575846/ce8f26f4-f030-4a2f-98df-0cbab19c5653">

According to my recent benchmark, only pre-training is significantly better than the default parameters:

- https://github.com/open-spaced-repetition/fsrs-benchmark/pull/44

<img width="557" alt="image" src="https://github.com/open-spaced-repetition/fsrs-rs/assets/32575846/776b20cc-0990-439b-a32e-70b054bf0c4a">

So I think we could allow users to optimize their FSRS parameters even when the number of their reviews is less 1000.

It's pretty easy. Because pre-training only provides the first four weights of FSRS. The related code is:

https://github.com/open-spaced-repetition/fsrs-rs/blob/51d38b48d0677775f71c6ab6614dbd15bfeed920/src/training.rs#L260-L263

We can pass an option to FSRS and let FSRS skip the rest of code, replace the first four weights of the default parameters and return the final weights.

A threshold of number of reviews is still necessary. 100~200 is fine. Then the user will enjoy the benefit of personalized parameters sooner.

@dae, what do you think?

**Comment by dae** [comment]
Users could accumulate 100 reviews in the first few days of use. Can you be confident about the inferred weights after such a short amount of time?

**Comment by L-M-Sherlock** [comment]
For inferring the initial stability, we only need to fit the first forgetting curve. Ideally, the user obeys the default schedule perfectly, then we could use all 100 reviews to estimate the probability in the first forgetting curve. It's a simple Bernoulli Distribution. In worst case, the error of estimating retention is $\frac{1}{2\sqrt{N}}$. Let N = 100, then error is 5%. It's good enough. But considering we have four initial stability for four ratings, so maybe 400?

**Comment by dae** [comment]
If you think it's worth doing, it's ok with me. We could optionally also require a minimum # of days between the first revlog entry and the current day if it proves to be a problem.

**Comment by L-M-Sherlock** [comment]
> If you think it's worth doing, it's ok with me.

OK. Let's talk about the API. Should I add an extra argument to the `compute_weights`? Its name may be `skip_training` or `only_pretraining`.

**Comment by dae** [comment]
If you want the cutoff to be based on # of revlog items, that would make sense, as it will be harder to count them inside the FSRS crate after they've been turned into FSRSItems.
