### ISSUE TITLE
Tests should be in a tests folder

### ISSUE THREAD

**Issue by Kees-van-Beilen** [open-spaced-repetition/fsrs-rs#178]
Currently the source code includes tests which depend on crates not present in the rest of the library. For instance rusqlite, which should be marked as an dev dependency as soon as the test files are relocated

**Comment by L-M-Sherlock** [comment]
It has been marked as an dev dependency:

https://github.com/open-spaced-repetition/fsrs-rs/blob/80da768907719972d9d674e6bbc046e564766e91/Cargo.toml#L44-L49

**Comment by dae** [comment]
I disagree with the other suggestion too. They are unit tests that depend on non-public API, so they don't belong in tests/.
