### ISSUE TITLE
Hide training behind feature flags

### ISSUE THREAD

**Issue by haasal** [open-spaced-repetition/fsrs-rs#210]
The crate has a massive amount of (nested) dependencies which are mainly relevant (I guess?) for training the model. For someone using this crate only to do predictions on the default weights this is a huge overhead.

I propose adding feature flags like `scheduler` and `optimizer` and optional dependencies to some parts of the code to cut down on the dependency amount.

I think mainly burn is causing this. Also the `rusqlite` version is slightly outdated. Which isn't a huge problem but a bit annoying.

**Comment by L-M-Sherlock** [comment]
> For someone using this crate only to do predictions on the default weights this is a huge overhead.

I guess you want this: https://github.com/open-spaced-repetition/rs-fsrs

**Comment by haasal** [comment]
More or less. It seemed to me that the crate isn't maintained as I didn't find the weights in any of the FSRS' versions in the wiki. This is the main crate everyone will see first. Also referring to another crate unfortunately doesn't solve the problem here. I would help on working on this but I would need some help.

**Comment by L-M-Sherlock** [comment]
fsrs-rs is a crate used to optimize the parameters for Anki. It's the initial goal of the project. If you want to use it only to do predictions on the default weights, there will be a lot of work to do. PR is welcome.
