### ISSUE TITLE
Question: Recommended amount of reviews before optimizing?

### ISSUE THREAD

**Issue by joshdavham** [open-spaced-repetition/fsrs-rs#211]
Is there a minimum recommended amount of reviews one should have before running the optimizer?

For example, if I have 5 cards that have only been reviewed three times each, I imagine that this is not enough to warrant running the optimizer as it could lead to bad weights. If this is the case, what is the minimum amount of reviews before optimization makes sense?

**Comment by L-M-Sherlock** [comment]
We have considered it here:

https://github.com/open-spaced-repetition/fsrs-rs/blob/ea80c61ac0cfc6847a19d0ea3d63eaae4947e87c/src/training.rs#L211-L227

If the reviews are not enough, the optimizer will just return the default parameters, or just skip training.

**Comment by joshdavham** [comment]
Makes sense. Also, I really need to learn Rust at some point!
