### ISSUE TITLE
Increase the number of epochs to 10

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs-rs#218]
According to the [benchmark results](https://github.com/open-spaced-repetition/srs-benchmark), FSRS-rs underperforms the Python version. While it's not a catastrophically large difference, it would be nice to try and bridge the gap. The only simple way of doing it that I can think of is training FSRS-rs for more epochs.

**Comment by dae** [comment]
> While it's not a catastrophically large difference

It's rather small as far as I can tell, and I'm not sure it makes sense to throw a bunch of extra computing resources at it to squeeze out a tiny improvement.

**Comment by L-M-Sherlock** [comment]
IMO, the current result is good enough. I have tried different combinations of hype-parameters, but none of them improved the metrics significantly.
