### ISSUE TITLE
more examples on how to use this crate?

### ISSUE THREAD

**Issue by asukaminato0721** [open-spaced-repetition/fsrs-rs#228]
like how to use those public apis.

how to optimize the parameters.

**Comment by L-M-Sherlock** [comment]
Where to add the examples?

**Comment by asukaminato0721** [comment]
> Where to add the examples?

add an `example/` folder and run it in ci, link it in the readme.

**Comment by asukaminato0721** [comment]
`#[test]` may be used in test private functions, but examples are for normal users to read.

**Comment by L-M-Sherlock** [comment]
Add an example:
- #244 

TODO:
- [ ] optimization
- [ ] migration
