### ISSUE TITLE
your/tensor library issue

### ISSUE THREAD

**Issue by sineptic** [open-spaced-repetition/fsrs-rs#232]
I'm trying to understand how use this library(to my project) and now try to compute params.
``` rust
use fsrs::{DEFAULT_PARAMETERS, FSRS};

fn main() {
    let fsrs = FSRS::new(Some(&DEFAULT_PARAMETERS)).unwrap();

    let item2 = fsrs::FSRSItem {
        reviews: vec![
            fsrs::FSRSReview {
                rating: 1,
                delta_t: 1,
            },
            fsrs::FSRSReview {
                rating: 1,
                delta_t: 1,
            },
        ],
    };
    let item1 = fsrs::FSRSItem {
        reviews: vec![fsrs::FSRSReview {
            rating: 1,
            delta_t: 1,
        }],
    };

    let mut items = vec![item1; 62];
    items.push(item2);

    let _best_params = fsrs.compute_parameters(items, None).unwrap();
}
```
This code works, but when
``` rust
    let mut items = vec![item1; 63];
```
program panics with this:
```
thread 'main' panicked at /home/sineptic/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ndarray-0.15.6/src/impl_methods.rs:1035:21:
ndarray: index 18446744073709551615 is out of bounds in array of len 19
```
`18446744073709551615` = 2 ^ 64 - 1

last place in YOUR library before panic is model.rs:100 in this function:
``` rust
pub(crate) fn init_stability(&self, rating: Tensor<B, 1>) -> Tensor<B, 1> {
    self.w.val().select(0, rating.int() - 1)
}
```
And whats interesting, if items len < 64, this function never invoces(in my example)

**Comment by L-M-Sherlock** [comment]
I guess it's an issue from upstream (the [burn](https://github.com/tracel-ai/burn) crate).

**Comment by sineptic** [comment]
Maybe, i dont dont know this lib, bujt as i say, on 63 items this(in your codebase) function arent ivoked

**Comment by L-M-Sherlock** [comment]
After debugging your code, I find out the problem.

1. The first review's delta_t should be 0 because it's the first review, so the delta_t since the last review doesn't exist.
2. The FSRSItem should include two FSRSReview at least, because it consists of the feature part and label part.

**Comment by sineptic** [comment]
1. What if I create card today, but first review is tomorrow?
2. what are `feature part` and `label part`?

**Comment by L-M-Sherlock** [comment]
> * What if I create card today, but first review is tomorrow?

The delta_t review remains zero because FSRS does not take into account the card's creation time.

> 2\. what are `feature part` and `label part`?

The final long-term review serves as the label portion, which the model predicts. The reviews preceding the last long-term review constitute the feature set upon which the prediction is based.

**Comment by asukaminato0721** [comment]
Seems fixed, so close, feel free to reopen it or open a new issue.
