### ISSUE TITLE
[Question] How should I round delta_t in FSRSReview?

### ISSUE THREAD

**Issue by sineptic** [open-spaced-repetition/fsrs-rs#237]
How I should round `delta_t` in `FSRSReview`?
- 0.3 -> 0?
- 0.5 -> ???
- 0.9 -> 1?

**Comment by L-M-Sherlock** [comment]
If the reviews are done in the same subjective day (start from waking and end at sleeping), `delta_t` should be 0. If the user sleeps once between two reviews, the `delta_t` is 1. Because we don't know whether the user sleeps or not, we need timezone or `next_day_start_at`.

https://github.com/open-spaced-repetition/fsrs-rs/blob/e7b4a48497a27733352b44f01868f5d1dc059afa/src/convertor_tests.rs#L102-L106

**Comment by sineptic** [comment]
> Because we don't know whether the user sleeps or not, we need timezone ...

I understand idea, but don't understand is there any differences in example when using chrono::DateTime insted of SystemTime.

``` rust
use chrono::prelude::*;
fn main() {
    let now = Utc::now();
    let time1 = now + chrono::Duration::seconds(24 * 60 * 60 - 1);
    let time2 = now + chrono::Duration::seconds(24 * 60 * 60);
    assert_eq!((time1 - now).num_days(), 0);
    assert_eq!((time2 - now).num_days(), 1);
}
// This lib counts time and round to days, but doesn't count "days"
```

**Comment by sineptic** [comment]
``` rust
use chrono::prelude::*;

fn sleeps_between(first: impl Datelike, second: impl Datelike) -> i32 {
    let diff = second.num_days_from_ce() - first.num_days_from_ce();
    if diff > 0 {
        diff - 1
    } else if diff < 0 {
        diff + 1
    } else {
        0
    }
}

fn main() {
    let now = Utc::now();
    let time1 = now + chrono::Duration::seconds(86400 + 60 * (60 * 6 - 20));
    let time2 = now + chrono::Duration::seconds(86400 + 60 * 60 * 6);

    // Result for me now
    dbg!(sleeps_between(now, time1)); // 0
    dbg!(sleeps_between(now, time2)); // 1
}
```
Seems be correct and I want to add this function to crate

**Comment by L-M-Sherlock** [comment]
I think they are equivalence:

https://github.com/open-spaced-repetition/fsrs-rs/blob/aee65ba37c1b39719ec6182050b282fd137ecbe6/examples/optimize.rs#L180-L187

**Comment by sineptic** [comment]
why? num days doesn't depend on starting time.

(01:00 - 23:00).num_days() == 0

sleeps_between(23:00,  01:00) == 1

**Comment by L-M-Sherlock** [comment]
The example is simplified. You can shift the dates by starting time before passing them into `convert_to_fsrs_item`.
