### ISSUE TITLE
[Question] What is the meaning of applying `FSRS::next_interval` to a new card?

### ISSUE THREAD

**Issue by sineptic** [open-spaced-repetition/fsrs-rs#243]
In `FSRS::next_interval`:
```
Stability should be provided except when the card is new.
```
But as I understand next_interval for new cards doesn't have any meaning, because they might be reviewed immediately after creation.

**Comment by L-M-Sherlock** [comment]
https://github.com/open-spaced-repetition/fsrs-rs/blob/4f181264af6060c1fbcba05f09256a180cda1e9f/src/inference.rs#L137-L156

> But as I understand next_interval for new cards doesn't have any meaning

When the user rates the new card in their first learning, FSRS will calculate the initial stability of the card based on the rating,  and assign a interval for the new card.

**Comment by sineptic** [comment]
In what meaning `new card`?
- as a card, that have 0 recalls
- as a card, that have 1 recall

**Comment by sineptic** [comment]
???
calling next_interval should modify card?

**Comment by L-M-Sherlock** [comment]
I don't mean that you must modify the card. But you're likely to modify the card after applying `next_interval`, because `next_interval` is called when the user rates the card.

**Comment by L-M-Sherlock** [comment]
I don't recommend calculating repetition time for all cards. Instead, it's better to maintain two queues to separate new cards and review cards. A new card doesn't have repetition time until the user reviews it.

But if you still insist on calculating it, you cannot use `next_interval` because you didn't have `rating` for a new card when creating it.

**Comment by sineptic** [comment]
So my initial struggle:

>  you cannot use next_interval because you didn't have rating for a new card when creating it.

docs: 
```
Stability should be provided except when the card is new.
```

**Comment by L-M-Sherlock** [comment]
So just use `UNIX_EPOCH`

**Comment by sineptic** [comment]
Thank you. But I it is OK, that this is in docs? Or it has use case, that I dont need?

**Comment by L-M-Sherlock** [comment]
I add some examples here: https://github.com/open-spaced-repetition/fsrs-rs/blob/main/examples/schedule.rs

You can refer to them.
