### ISSUE TITLE
Auto merge main into fsrs-browser failed

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/fsrs-rs#247]
After merging #246, the action failed. For details, see: https://github.com/open-spaced-repetition/fsrs-rs/actions/runs/11547276816/job/32136903375

**Comment by AlexErrant** [comment]
I'm going to wait until [the burn v0.15.0 upgrade](https://github.com/open-spaced-repetition/fsrs-rs/pull/251) is complete to batch all the work together since the merge action failed due to a burn update.

**Comment by L-M-Sherlock** [comment]
I would wait for burn v0.16.0. The v0.15.0 slows down the training. I guess the next release won't happen soon. By the way, I'm curious whether burn has supported wasm with multi-threading. If so, we may not need to maintain a fork.

**Comment by L-M-Sherlock** [comment]
closed by e35f1c5fe531b9db5be3432df11fcf18b63111f2

**Comment by L-M-Sherlock** [comment]
Fine. I can wait. The patch only improves 6% performance of FSRS. When will Rust support it? 2025?

**Comment by AlexErrant** [comment]
As far as I can tell, it's not being actively worked on: https://github.com/rust-lang/rust/issues/77839

So no ETA >_>
