### ISSUE TITLE
Unwanted panic

### ISSUE THREAD

**Issue by sineptic** [open-spaced-repetition/fsrs-rs#248]
I expect, that when I (or other user of application) try optimize parameters, application do it successfully or display, that couldn't do this, but it crushes.

Reason: 
```
thread 'main' panicked at /..../fsrs-1.4.1/src/dataset.rs:54:14
```
this is on version 1.4.1. On main branch this line moves down and have number `55`.

Please make it return error.

**Comment by L-M-Sherlock** [comment]
https://github.com/open-spaced-repetition/fsrs-rs/blob/9d5d2f3ef19eb0584f333376d0a4c8a75120adfc/src/dataset.rs#L49-L55

I guess you pass a FSRSItem without any long term review.

**Comment by sineptic** [comment]
Yes, but the library doesn't say anything about this. What conditions should I check to guarantee that I do not panic?

**Comment by L-M-Sherlock** [comment]
https://github.com/open-spaced-repetition/fsrs-rs/blob/9d5d2f3ef19eb0584f333376d0a4c8a75120adfc/examples/optimize.rs#L175-L193

This example filters out FSRSItem which doesn't have long term review.

**Comment by sineptic** [comment]
But is there other conditions, that could lead to panic?

**Comment by L-M-Sherlock** [comment]
I think there isn't.

https://github.com/open-spaced-repetition/fsrs-rs/blob/9d5d2f3ef19eb0584f333376d0a4c8a75120adfc/src/dataset.rs#L42-L47

If `long_term_review_cnt` > 0, there must exist a review whose delta_t is greater than 0.

**Comment by sineptic** [comment]
Thank you so much. After I try optimizing parameters, that part of application that depend on your library will be completed.
