### ISSUE TITLE
[TODO] support sample weights when training

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/fsrs-rs#256]
It will make these possible:
- give more weights on post-lapse reviews to improve the accuracy on post-lapse stability.
- give more weights on recent reviews (Time Decay) to fit the learner's current memory pattern and review habit.

fsrs-optimizer has supported it: https://github.com/open-spaced-repetition/fsrs-optimizer/pull/152

**Comment by brishtibheja** [comment]
This is probably going to improve things for end-user but when we update our Anki and optimise, this should result in worse log-loss in which Anki will just retain the previous parameters instead of updating them. Wdyt about that?

**Comment by L-M-Sherlock** [comment]
> This is probably going to improve things for end-user but when we update our Anki and optimise, this should result in worse log-loss in which Anki will just retain the previous parameters instead of updating them. Wdyt about that?

Maybe we need apply the weights in the evaluation, too.

**Comment by Expertium** [comment]
I've said this before - if we apply weights during both evaluation and training, then loss values will effectively become arbitrary since they depend on the weighting function.
