### ISSUE TITLE
Support for Online Learning?

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs-rs#56]
@L-M-Sherlock, you mentioned that you plan to implement the online learning version of the FSRS optimizer in Anki. (https://github.com/open-spaced-repetition/fsrs-vs-sm15/issues/36#issuecomment-1686492460)

But does this version support online learning? I am asking this I didn't see any mention of experience replay in this repo.

**Comment by L-M-Sherlock** [comment]
To implement it, we need to integrate the scheduler into Anki at first. By the way, online learning doesn't mean that it must have experience replay. The main feature of online learning is it could optimize its current weights by the new reviews on the fly.

**Comment by L-M-Sherlock** [comment]
There are two ways for auto-optimization: Online Learning and Periodic Retraining. I prefer the latter because it is easier to implement and more stable.
