### ISSUE TITLE
[Feature Request[ Use two different sets of initial parameters, then average out the results

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs-rs#84]
This version doesn't use splits, so instead I propose a different approach. Obtain 2 different sets of initial parameters by running this version on 70+ collections of users, taking the number of reviews and the optimal parameters, and calculating optimal parameters weighted by `n_reviews` and `ln(n_reviews)`. Since the weighting is different, those 2 sets will also be different.
Then use these 2 sets of parameters to run the optimizer twice. First, using one set (say, the one that was obtaiend by weighting by n_reviews) of initial parameters, then using the other set. Then average the result.
The key idea is that instead of using one starting point in the space of all possible configurations of parameters, we use two starting points. This could improve convergence without using splits.

Preparing the sets of initial parameters:
1) Run the optimizer on each available collection
2) Record optimal parameters and n_reviews for each user
3) Obtain set 1 by using a weighted average (weighted by n_reviews)
4) Obtain set 2 by using a weighted average (weighted by ln(n_reviews))

Deployment:
1) The user chooses a preset/deck/collection
2) Optimization starts with initial parameters from set 1
3) Optimization ends, optimal parameters are recorded (optimal parameters for this user, set 1)
4) Optimization starts with initial parameters from set 2
5) Optimization ends, optimal parameters are recorded (optimal parameters for this user, set 2)
6) Use a simple arithmetic average to obtain the final set of optimal parameters by averaging the values in two sets of optimal parameters, return that final set to the user

**Comment by L-M-Sherlock** [comment]
Before we improve the Rust version optimizer, we should develop an automatic evaluation tool. Without evaluation, we cannot determine whether the idea works. But I’m still not skilled in Rust, it would take a long time. By the way, I have tested many methods to make the optimal parameters stable, but they don’t work. And the float point number calculation is not consistent in different platforms, it is possible that the final parameters are different even when you use the same code and data.

**Comment by asukaminato0721** [comment]
some thoughts:
1. could that `automatic evaluation tool` be developed in an easy language like python ? (I am not sure how it will be used though). And if it has a python prototype, rewrite (if necessary) would be much easier, I guess.
2. And the float point number calculation is not consistent.
    https://github.com/paupino/rust-decimal or https://github.com/mamrhein/fpdec.rs ? But I am not sure about the performance.

**Comment by L-M-Sherlock** [comment]
> 1. could that `automatic evaluation tool` be developed in an easy language like python

https://github.com/open-spaced-repetition/fsrs-benchmark

**Comment by user1823** [comment]
This issue is out-of-date.
