### ISSUE TITLE
Use the first revlog in the "known" review history for converting SM-2 ivl & ease to memory states

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs-rs#87]
In Anki 23.10 beta 3, for cards with incomplete review history, Anki is using the _last_ revlog entry to calculate memory states from SM-2 ivl and ease. However, I recommend using the _first_ revlog entry. The reason is simple: The earlier we can calculate the memory states, the more accurate the results will be.

I described the algorithm for approaching such cards here: https://github.com/open-spaced-repetition/fsrs-rs/issues/63#issuecomment-1735323658

I implemented the same thing in the Helper add-on (with help from @L-M-Sherlock) in this PR: https://github.com/open-spaced-repetition/fsrs4anki-helper/pull/248

Screenshots:

Memory states calculated using Anki:
<img width="540" alt="image" src="https://github.com/open-spaced-repetition/fsrs-rs/assets/92206575/78038734-efaa-41f1-a4dc-175ceffe0a4c">

Memory states calculated using Helper add-on
<img width="539" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/67e2f9a6-d3b7-4607-9c53-35bfd1e762fc">

**Comment by user1823** [comment]
How does it make the converter too complex? Instead of using the last revlog entry, we are just using the first one and then the subsequent reviews of the same card are handled in the same way the reviews of normal cards are handled.

**Comment by L-M-Sherlock** [comment]
Because it requires the full review history. The current method only requires the latest review log.

**Comment by user1823** [comment]
> Because it requires the full review history. 

Calculation of memory states for the first time requires the full review history for all cards, not just these cards.

After each subsequent review, the memory states can be updated by using just the current review and the memory states after the last review, just like any other card.

Frankly, I don't understand how my proposed solution is different from the approach used for any other "normal" card except for using `memory_state_from_sm2` function instead of `init_states` function at the first revlog entry.

**Comment by L-M-Sherlock** [comment]
Because the Rust code doesn't work in the same way as the helper add-on. The calculation of memory states and optimization share the same function. It's tricky to re-implement the same thing I implemented in the helper add-on.

**Comment by user1823** [comment]
Ok, then let @dae have a look on this.

**Comment by dae** [comment]
The revlog is not used when calculating memory state - only the card's current ease and interval are. The last revlog entry is used when answering cards, to determine the time elapsed since the last review.

I'm not sure why you feel using the first revlog entry would be better. Then you'd be assigning the card the memory state it had at that point in time, which may well differ from its current state. If you were then to replay all the subsequent reviews to derive the current memory state that might make more sense, but it's a bunch of extra work, and since revlogs tend to be truncated at the start rather than the end, you're probably not going to capture the first rating anyway. Your solution in the helper also doesn't handle cases where the user has used set due date to introduce the card, or when the first remaining revlog entry happens to be relearning or reviewing ahead.

**Comment by user1823** [comment]
> I'm not sure why you feel using the first revlog entry would be better.

One of the strengths of FSRS is that the SInc (ratio of two consecutive stabilities) decreases over time even if the user presses Good every time. But, this is not the case with SM-2. So, if we can estimate the memory states from the first "known" review, they will be more accurate than the memory states estimated from the current interval and ease.

>  If you were then to replay all the subsequent reviews to derive the current memory state that might make more sense, but it's a bunch of extra work,

It is definitely extra work as compared to just using the current ease and ivl. But, we use all the reviews to calculate the memory states for all the other "normal" cards. So, if you compare it to the "normal", it is not an extra work (at least in terms of computing resources needed). However, I agree that implementing this will need editing the code (once) so that increases the workload of the devs.

> you're probably not going to capture the first rating anyway.

Yes, but as I said above, the earlier review we can use, the better the results will be. So, even if we can't capture the first rating, we are still better off as compared to using the last rating.

> Your solution in the helper also doesn't handle cases where the user has used set due date to introduce the card

As Jarrett informed, in this case, the first rating will be filtered out (because the helper filters out the set due date ratings) and then the next rating will be considered as the first rating. This seems to be a reasonable way to deal with such cards.

> or when the first remaining revlog entry happens to be relearning or reviewing ahead.

That is a TODO.

**Comment by dae** [comment]
I will change it so that the revlog is used if available, and it will fall back to the current card state if there are no non-manual entries in the revlog.

**Comment by user1823** [comment]
> I will change it so that the revlog is used if available

In https://github.com/ankitects/anki/commit/d16faacd0f37e14386b1980cca7e1483686a9164, I think that the change is to use the "normal" method of calculating the memory states if any reviews are available (Please excuse me if I am wrong, I am not a dev). But, this will re-create the problem that I described in https://github.com/open-spaced-repetition/fsrs-rs/issues/63#issuecomment-1733680388 (the interval decreasing drastically).

So, please consider implementing my suggestion, which is described in https://github.com/open-spaced-repetition/fsrs-rs/issues/63#issuecomment-1735323658. This will benefit many users (incl. me) who have cards with incomplete revlogs.

I know that it will be difficult to implement because unlike the python version, the rust version uses the same code for training and calculation of memory states. But, I don't think that it will be impossible to implement my suggestion.

To be clear, in my opinion, such incomplete revlogs shouldn't be used in training but should be used for calculating memory states (after the initial memory states of such cards have been calculated from SM-2).

**Comment by user1823** [comment]
I decided to have a (slightly) more focused review of the code used for training and calculating the memory states and I made an observation. But firstly, I want to re-iterate that I am not a dev. So, take my observations with a grain of salt.

The following code ignores cards without any learning steps during training. So, implementing my suggestion (https://github.com/open-spaced-repetition/fsrs-rs/issues/63#issuecomment-1735323658) might be easier than it appears. (continue reading below the code block)
```rs
    } else if training {
        // when training, we ignore cards that don't have any learning steps
        return None;
    }
```

With the above small code, we effectively have different datasets for training and calculating memory states. If I understand it correctly, this was the main obstacle in implementing my suggestion. So, in my opinion, to implement my suggestion, we just need to make some modifications in the following code block:
```rs
impl Card {
    pub(crate) fn set_memory_state(&mut self, fsrs: &FSRS, item: Option<FSRSItem>) {
        self.memory_state = item
            .map(|i| fsrs.memory_state(i))
            .or_else(|| {
                if self.ctype == CardType::New {
                    None
                } else {
                    Some(fsrs.memory_state_from_sm2(self.ease_factor(), self.interval as f32))
                }
            })
            .map(Into::into);
    }
}
```

Imo, the required change would be to add a code similar to this (truncated) code of the helper add-on, with appropriate changes (for e.g., replacing `continue` with something like `fsrs.memory_state(i)` for subsequent reviews of the same card) : 
```py
        if i == 0 and (
            revlog.review_kind == REVLOG_REV
            or (revlog.review_kind == REVLOG_CRAM and revlog.ease != 0)
        ):
            s, d = fsrs.memory_state_from_sm2(
                revlog.ease / 1000, max(revlog.interval / 86400, 0.1), retention
            )
            s = max(0.1, min(s, 36500))
            d = constrain_difficulty(d)
            continue 
```

**Comment by L-M-Sherlock** [comment]
To implement it, we need to pass the converted memory state into the model as the initial memory state. It requires to re-write the forward function.

**Comment by dae** [comment]
Ok, with Jarret's comment I think I now understand the point you were trying to make, user1823.

I think it's unlikely that the user would lose revlog entries in the middle, as revlogs are always merged when syncing, and when users remove old revlogs to save space, they tend to do so from the oldest entries.

I will push a PR that enables this, but will defer to Jarret on this - if he thinks it's better to derive the memory state from the current card state, I can undo the change.
